[[requestmapClass]]
=== Requestmap Class

Optionally, use this class to store request mapping entries in the database instead of defining them with annotations or in `application.groovy`. This option makes the class configurable at runtime; you can add, remove and edit rules without restarting your application.

.Requestmap class configuration options
[cols="30,30,40"]
|====================
| *Property* | *Default Value* | *Meaning*

|requestMap.className
|_none_
|requestmap class name

|requestMap.urlField
|"`url`"
|URL pattern property name

|requestMap.configAttributeField
|"`configAttribute`"
|authority pattern property name

|requestMap.httpMethodField
|"`httpMethod`"
|HTTP method property name (optional, does not have to exist in the class if you don't require URL/method security)
|====================

Assuming you choose `com.mycompany.myapp` as your package, and `Requestmap` as your class name, you'll generate this class:

[source,groovy]
.`Requestmap.groovy`
----
package com.mycompany.myapp

import org.springframework.http.HttpMethod

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes=['configAttribute', 'httpMethod', 'url'])
@ToString(includes=['configAttribute', 'httpMethod', 'url'], cache=true, includeNames=true, includePackage=false)
class Requestmap implements Serializable {

   private static final long serialVersionUID = 1

   String configAttribute
   HttpMethod httpMethod
   String url

   Requestmap(String url, String configAttribute, HttpMethod httpMethod = null) {
      this()
      this.configAttribute = configAttribute
      this.httpMethod = httpMethod
      this.url = url
   }

   static constraints = {
      configAttribute blank: false
      httpMethod nullable: true
      url blank: false, unique: 'httpMethod'
   }

   static mapping = {
      cache true
   }
}
----

To use Requestmap entries to guard URLs, see <<requestmapInstances>>.
