grails.doc.authors = 'Burt Beckwith, Beverley Talbott'
grails.doc.license = 'Apache License 2.0'
grails.doc.title = 'Spring Security Core Plugin'
//grails.doc.subtitle = ''
//grails.doc.copyright = ''
//grails.doc.footer = ''
